#!/usr/bin/env bash

[ -L $0 ] && pushd `readlink $0 | xargs dirname` > /dev/null \
    || pushd `dirname $0` > /dev/null
export CONTI_PATH=`pwd -P`
popd > /dev/null

# Check if docker and docker-compose are available on trhe system
command -v docker >/dev/null 2>&1 || { echo "docker is not installed. Aborting." >&2; exit 1; }
command -v docker-compose >/dev/null 2>&1 || { echo "docker-compose is not installed. Aborting." >&2; exit 1; }

COMMAND=$1; shift;

[ ! -f ${CONTI_PATH}/plugins/${COMMAND} ] && usage
${CONTI_PATH}/plugins/${COMMAND} "$@"
