version: "2"

services:

  nginx:
    image: "###IMAGE_NGINX###"
    links:
      - "php"
    ports:
      - "80"
    env_file:
      - ./.env

  php:
    image: "###IMAGE_PHP###"
    env_file:
      - ./.env

  mysql:
    image: "###IMAGE_MARIADB###"
    command: "--character-set-server=utf8 --collation-server=utf8_unicode_ci"
    volumes:
      - ${MYSQL_PERSISTENCE_FOLDER}:/var/lib/mysql
      - ${MYSQL_BACKUP_FOLDER}:/mysql-backup
    env_file:
      - ./.env

  composer:
    image: "###IMAGE_COMPOSER###"
    env_file:
      - ./.env
    working_dir: "/app/"

  nodejs:
    image: "###IMAGE_NODEJS###"

  mailcatcher:
    image: "###IMAGE_MAILCATCHER###"
    ports:
      - 1080:1080