#!/usr/bin/env bash

start() {
    docker-compose up -d
}

stop() {
    docker-compose down --remove-orphans $@
}

status() {
    docker-compose ps $@
}

restart() {
    environment_stop
    environment_start
}

pull() {
    docker-compose pull
}

upgrade() {
    while true; do
    read -p "Do you really want to upgrade your development environment? " yn
    case $yn in
        [Yy]* ) pull; restart; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no. Choose wisely ;)" ;;
    esac
done
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    pull)
        pull
        ;;
    status)
        status
        ;;
    upgrade)
        upgrade
        ;;
    *)
        start "$@"
        ;;
esac