#!/usr/bin/env bash

redis() {
    docker-compose exec --user=1000:33 redis redis-cli
}

monitor() {
    docker-compose exec --user=1000:33 redis redis-cli MONITOR
}

info() {
    docker-compose exec --user=1000:33 redis redis-cli INFO
}

ping() {
    docker-compose exec --user=1000:33 redis redis-cli PING
}

case "$1" in
    monitor)
        monitor
        ;;
    info)
        info
        ;;
    ping)
        ping
        ;;
    *)
        redis "$@"
        ;;
esac