#!/bin/bash

if [ -e "${DOCKER_COMPOSE_FILE}/docker-compose.yml" ] || [ -e "${DOCKER_ENV_FILE}" ]; then
    echo "There seems to be a docker setup already. If you want create a new one please run '${APP_NAME} uninstall' first . Aborting."
    exit 1
fi

readonly DOMAIN=${1}
if [ "${DOMAIN}" == "" ]; then
    echo "You need a domain name to access you website? Run '${APP_NAME} install' www.domain.docker"
    exit 1
fi

cat ${CONTI_TEMPLATE_FOLDER}/docker-compose.yml | \
    sed -e "s#{{ IMAGE_MARIADB }}#${IMAGE_MARIADB}#g" | \
    sed -e "s#{{ IMAGE_NGINX }}#${IMAGE_NGINX}#g" | \
    sed -e "s#{{ IMAGE_PHP }}#${IMAGE_PHP}#g" | \
    sed -e "s#{{ IMAGE_COMPOSER }}#${IMAGE_COMPOSER}#g" | \
    sed -e "s#{{ IMAGE_MAILCATCHER }}#${IMAGE_MAILCATCHER}#g" | \
    sed -e "s#{{ IMAGE_REDIS }}#${IMAGE_REDIS}#g" \
    > $(pwd)/docker-compose.yml

cat ${CONTI_TEMPLATE_FOLDER}/.env | \
    sed -e "s#{{ MYSQL_ROOT_PASSWORD }}#$(pwgen -Bsv1 10)#g" | \
    sed -e "s#{{ MYSQL_PASSWORD }}#$(pwgen -Bsv1 10)#g" | \
    sed -e "s#{{ VIRTUAL_HOST }}#${DOMAIN}#g" \
    > $(pwd)/.env

if [ ! -d ${PROJECT_CONFIGURATION_FOLDER} ]; then
    mkdir ${PROJECT_CONFIGURATION_FOLDER}

    cp ${CONTI_TEMPLATE_FOLDER}/mariadb.cnf ${PROJECT_CONFIGURATION_FOLDER}/mariadb.cnf
    cp ${CONTI_TEMPLATE_FOLDER}/php-fpm.conf ${PROJECT_CONFIGURATION_FOLDER}/php-fpm.conf
    cp ${CONTI_TEMPLATE_FOLDER}/default.conf ${PROJECT_CONFIGURATION_FOLDER}/default.conf
fi