#!/bin/bash

if [ -e "${DOCKER_COMPOSE_FILE}/docker-compose.yml" ] || [ -e "${DOCKER_ENV_FILE}" ]; then
    echo "There seems to be a docker setup already. If you want create a new one please run '${APP_NAME} uninstall' first . Aborting."
    exit 1
fi

readonly DOMAIN=${1}
if [ "${DOMAIN}" == "" ]; then
    echo "You need a domain name to access you website? Run '${APP_NAME} install' www.domain.docker"
    exit 1
fi

cat ${TEMPLATES}/docker-compose.yml | \
    sed -e "s#{{ IMAGE_MARIADB }}#${IMAGE_MARIADB}#g" | \
    sed -e "s#{{ IMAGE_NGINX }}#${IMAGE_NGINX}#g" | \
    sed -e "s#{{ IMAGE_PHP }}#${IMAGE_PHP}#g" | \
    sed -e "s#{{ IMAGE_COMPOSER }}#${IMAGE_COMPOSER}#g" | \
    sed -e "s#{{ IMAGE_MAILCATCHER }}#${IMAGE_MAILCATCHER}#g" \
    > $(pwd)/docker-compose.yml

cat ${TEMPLATES}/.env | \
    sed -e "s#{{ MYSQL_ROOT_PASSWORD }}#$(pwgen -Bsv1 10)#g" | \
    sed -e "s#{{ MYSQL_PASSWORD }}#$(pwgen -Bsv1 10)#g" | \
    sed -e "s#{{ VIRTUAL_HOST }}#${DOMAIN}#g" \
    > $(pwd)/.env

echo "Done. docker-compose.yml and .env file have been created."