#!/usr/bin/env bash

source "./.env"

mysql() {
    docker-compose exec mysql mysql -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE $@
}

dump() {
    docker-compose exec mysql mysqldump -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE $@
}

import() {
    docker exec -i $(docker-compose ps | grep _db_ | awk '{print $1}') mysql -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE
}

case "$1" in
    mysql)
        mysql
        ;;
    dump)
        dump
        ;;
    import)
        import
        ;;
    *)
        mysql "$@"
        ;;
esac