version: '2'

services:

  nginx: 
    image: {{ IMAGE_NGINX }}
    ports:
      - 80
    env_file:
      - ./.env
    links: 
      - php
    volumes:
      - ${DATA_LOCATION}:/var/www/Web
      - /docker/conti/conti/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: {{ IMAGE_PHP }}
    env_file:
      - ./.env
    links:
      - mysql
      - mailcatcher
      - redis
    volumes:
      - ${DATA_LOCATION}:/var/www/Web

  mysql:
    image: {{ IMAGE_MARIADB }}
    volumes:
      - ${MYSQL_PERSISTENCE_FOLDER}:/var/lib/mysql
      - ${MYSQL_BACKUP_FOLDER}:/mysql-backup
      - /docker/conti/conti/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
    env_file:
      - ./.env

  composer:
    image: {{ IMAGE_COMPOSER }}
    env_file:
      - ./.env
    working_dir: /app/
    volumes:
      - ${DATA_LOCATION}:/app/
      - ~/.composer/:/composer/

  mailcatcher:
    image: {{ IMAGE_MAILCATCHER }}
    ports:
      - 1080:1080

  redis:
    image: {{ IMAGE_REDIS }}