version: '2'

services:

  nginx: 
    image: {{ IMAGE_NGINX }}
    ports:
      - 80
    env_file:
      - ./.env
    links: 
      - php
    volumes:
      - ${DATA_LOCATION}:/var/www/Web

  php:
    image: {{ IMAGE_PHP }}
    env_file:
      - ./.env
    links:
      - mysql
      - mailcatcher
      - redis
    volumes:
      - ${DATA_LOCATION}:/var/www/Web

  mysql:
    image: {{ IMAGE_MARIADB }}
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ${MYSQL_PERSISTENCE_FOLDER}:/var/lib/mysql
      - ${MYSQL_BACKUP_FOLDER}:/mysql-backup
    env_file:
      - ./.env

  composer:
    image: {{ IMAGE_COMPOSER }}
    env_file:
      - ./.env
    working_dir: /app/
    volumes:
      - ${DATA_LOCATION}:/app/
      - ~/.composer/:/composer/

  mailcatcher:
    image: {{ IMAGE_MAILCATCHER }}
    ports:
      - 1080:1080

  redis:
    image: {{ IMAGE_REDIS }}