version: '2'

services:

  nginx: 
    image: nginx:1.11
    ports:
      - 80
    env_file:
      - ./.env
    links: 
      - php
    volumes:
      - ${DATA_LOCATION}:/var/www/Web

  php:
    image: php:7-fpm
    env_file:
      - ./.env
    links:
      - mysql
    volumes:
      - ${DATA_LOCATION}:/var/www/Web

  mysql:
    image: mysql:5.6
    env_file:
      - ./.env

  composer:
    image: composer/composer:1.1
    env_file:
      - ./.env
    working_dir: /app/
    volumes:
      - ${DATA_LOCATION}:/app/
      - ~/.composer/:/composer/